### ISSUE TITLE
str_remove() is not working

### ISSUE THREAD

**Issue by jaynal83** [ryurko/fcscrapR#2]
I am getting this error. I have stringr 1.2.0 version installed and I cannot find str_remove() function there. Could you please let me know which version of stringr you are using?

Error in mutate_impl(.data, dots) : 
  Evaluation error: 'str_remove' is not an exported object from 'namespace:stringr'.

**Comment by ryurko** [comment]
Version 1.3.1 - just update the stringr package (or all of the tidyverse with install.packages('tidyverse') and you'll be good to go. Thanks for pointing this out though, I'll update the package version requirement.
