### ISSUE TITLE
small bug in the  code

### ISSUE THREAD

**Issue by iamrafael8** [ryurko/fcscrapR#3]
![image](https://user-images.githubusercontent.com/29176986/41907152-0ecb78f8-7951-11e8-90a0-79df70c0d9e5.png)

The number of colors shall be 5 instead of 4  in the example code

library(ggplot2)
srb_crc_commentary %>%
  dplyr::filter(!is.na(shot_result)) %>%
  ggplot(aes(x = shot_by_team, fill = shot_result)) +
  geom_bar() + labs(x = "Team", y = "Count", 
                    fill = "Shot result",
                    title = "Distribution of shot attempts for Costa Rica vs Serbia by result",
                    caption = "Data from ESPN, accessed with fcscrapR") +
  scale_fill_manual(values = c("darkorange", "darkblue", "darkred", "darkcyan")) +
  theme_bw()

**Comment by ryurko** [comment]
I'm not encountering the same error as you. This code example above was meant for the Serbia vs Costa Rica match, did you change the game id? Because other games could have own-goals which would be another type for shot_result causing it to be 5 instead of 4.

**Comment by iamrafael8** [comment]
Yes exactly, I have usedd Uruguay vs Russia which is not working because of the own goals

**Comment by ryurko** [comment]
Okay, then this isn't an issue with fcscrapR itself (unless the own goals are missing, which has been pointed out in another issue). Instead this is more of how to use ggplot and setting your color scale, with the ow_goal you now now 5 types of shot_result so you need to add another color to the vector inside scale_fill_manual() or use a different version scale_fill_ such as scale_fill_brewer(palette = "Set1") for example. Here's more info: http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
