### ISSUE TITLE
Extra Time Issue

### ISSUE THREAD

**Issue by lbenz730** [ryurko/fcscrapR#4]
There seems to be 2 issues related to Extra Time + Penalty shootouts. 
The first issue is that penalty shots during shootouts seem to be registering as regular goals, without the penalty shot flag. The second issue is that extra time is misrepresented when converted to numeric (120' --> 12), likely as a result of using substring or something similar. Both issues were noticed when I couldn't figure out why there was an early spike of goals across this World Cup!

<img width="616" alt="screen shot 2018-07-03 at 9 14 33 pm" src="https://user-images.githubusercontent.com/21962947/42251572-2038679e-7f06-11e8-86df-03513045f76d.png">

**Comment by ryurko** [comment]
Thanks - should be good to go now, let me know if see anything odd still! Penalty shootouts are marked by half == 5 and penalty_shot == 1, with two new columns marking the goals made during the penalty shootouts.
