### ISSUE TITLE
scrape_scoreboard_ids appears broken

### ISSUE THREAD

**Issue by NateLatshaw** [ryurko/fcscrapR#8]
Hey Ron,

The scrape_scoreboard_ids() function appears to no longer work.  I assume ESPN has made some changes in how they name scoreboards.

For instance, I can scrape today's commentary from the Southampton, Manchester United game using: scrape_commentary(541809)

However, the following commands return a "no matches available..." message:
scrape_scoreboard_ids()
scrape_scoreboard_ids(scoreboard_name = 'english premier league', game_date = '2019-08-31')

Also, from the documentation, the following command also returns no matches:
scrape_scoreboard_ids(scoreboard_name = "fifa world cup", game_date = "2018-06-20")

I'm not sure if you're still interested in updating this package - I appreciate all this work either way!

Nate

**Comment by ryurko** [comment]
Sorry for the delay but should be working now!
